# Generated by Django 2.1a1 on 2018-06-08 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brokers',
            name='title',
        ),
    ]
