# Generated by Django 2.1a1 on 2018-06-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analizy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analiza',
            name='waluta',
            field=models.CharField(default='EUR/USD', max_length=150),
        ),
    ]
