# Generated by Django 2.1a1 on 2018-06-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analizy', '0003_auto_20180603_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analiza',
            name='year_in_school',
            field=models.CharField(choices=[('FR', 'EUR/USD'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], default='FR', max_length=2),
        ),
    ]
