# Generated by Django 2.1a1 on 2018-06-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analizy', '0004_auto_20180603_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analiza',
            name='year_in_school',
            field=models.CharField(choices=[('EUR/USD', 'EUR/USD'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], default='EUR/USD', max_length=2),
        ),
    ]
