# Generated by Django 2.1a1 on 2018-06-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analizy', '0008_auto_20180603_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analiza',
            name='instrument',
            field=models.CharField(choices=[('EUR/USD', 'EUR/USD'), ('USD/JPY', 'USD/JPY')], default='EUR/USD', max_length=200),
        ),
    ]
