# Generated by Django 2.1a1 on 2018-06-03 10:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180516_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_header',
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
